[build]
  command = "echo 'No build required for static site'"
  publish = "."

[build.environment]
  PYTHON_VERSION = "3.9.18"

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/app/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 