[build]
  base = "."
  command = "chmod +x build.sh && ./build.sh"
  publish = "static"
  
[build.environment]
  PYTHON_VERSION = "3.9"
  FLASK_ENV = "production"
  FLASK_DEBUG = "False"
  
[functions]
  directory = "netlify/functions"
  python_version = "3.9"
  
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/app/:splat"
  status = 200
  force = true
  
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  
[dev]
  command = "python web_app.py"
  port = 8080
  targetPort = 8080
  publish = "static" 